import test from 'node:test';import assert from 'node:assert/strict';
import ganache from 'ganache';
import {BrowserProvider,Wallet,NonceManager,Contract,ContractFactory,keccak256,toUtf8Bytes} from 'ethers';
import {readFileSync} from 'node:fs';
import {EmberFinance,BEM,amountRaw,finishPayment,normalized,artifact} from '../server/finance.mjs';
const types={Ticket:[{name:'id',type:'bytes32'},{name:'a',type:'address'},{name:'b',type:'address'},{name:'asset',type:'uint8'},{name:'stake',type:'uint256'},{name:'fundUntil',type:'uint256'},{name:'rulesHash',type:'bytes32'}],Result:[{name:'id',type:'bytes32'},{name:'winner',type:'uint8'},{name:'endedAt',type:'uint256'},{name:'evidence',type:'bytes32'}],Cancel:[{name:'id',type:'bytes32'}]};
const mock=JSON.parse(readFileSync(new URL('./fixtures/arena-test-bem.json',import.meta.url))).ArenaTestBEM;
async function fixture(chainId=31337){const raw=ganache.provider({chain:{chainId},logging:{quiet:true},wallet:{totalAccounts:5}}),provider=new BrowserProvider(raw);provider.pollingInterval=10;const wallets=Object.values(raw.getInitialAccounts()).map(x=>new Wallet(x.secretKey,provider)),signers=wallets.map(w=>new NonceManager(w));let tok;if(chainId===196){await raw.request({method:'evm_setAccountCode',params:[BEM,mock.runtime]});tok=new Contract(BEM,mock.abi,signers[0]);}else{tok=await new ContractFactory(mock.abi,mock.bytecode,signers[0]).deploy();await tok.waitForDeployment();}const escrow=await new ContractFactory(artifact.abi,artifact.bytecode,signers[0]).deploy(wallets[3].address,wallets[0].address,await tok.getAddress());await escrow.waitForDeployment();const domain={name:'TapeOutEmber',version:'1',chainId,verifyingContract:await escrow.getAddress()};let serial=0;const sign=(name,value)=>wallets[3].signTypedData(domain,{[name]:types[name]},value),time=async()=>Number((await raw.request({method:'eth_getBlockByNumber',params:['latest',false]})).timestamp);return{raw,provider,wallets,signers,tok,escrow,sign,time,async ticket(asset=0){return{id:keccak256(toUtf8Bytes('match'+(++serial))),a:wallets[1].address,b:wallets[2].address,asset,stake:asset===0?10n**16n:10n**8n,fundUntil:await time()+180,rulesHash:keccak256(toUtf8Bytes('rules'))}},async advance(n){await raw.request({method:'evm_increaseTime',params:[n]});await raw.request({method:'evm_mine',params:[]});},async close(){provider.destroy();await raw.disconnect();}};}
async function fund(f,t){const sig=await f.sign('Ticket',t);for(const i of[1,2]){if(t.asset===1){await(await f.tok.connect(f.signers[i]).claim()).wait();await(await f.tok.connect(f.signers[i]).approve(await f.escrow.getAddress(),t.stake)).wait();}await(await f.escrow.connect(f.signers[i]).fund(t,sig,{value:t.asset===0?t.stake:0})).wait();}}
test('OKB escrow: equal funding, 60s wait, 10% fee, exact per-match withdrawal, owner cannot take liability',async()=>{const f=await fixture();try{const t=await f.ticket();await fund(f,t);assert.equal(await f.escrow.liability(0),t.stake*2n);await assert.rejects(f.escrow.withdrawPlatform.staticCall(0,f.wallets[0].address,1));const r={id:t.id,winner:0,endedAt:await f.time(),evidence:t.rulesHash},sig=await f.sign('Result',r);await assert.rejects(f.escrow.connect(f.signers[1]).claim.staticCall(r,sig));await f.advance(61);await(await f.escrow.connect(f.signers[1]).claim(r,sig,{gasLimit:500000})).wait();const m=await f.escrow.getMatch(t.id);assert.equal(m.payout[0],t.stake*18n/10n);assert.equal(m.withdrawn[0],true);assert.equal(await f.escrow.liability(0),0n);assert.equal(await f.escrow.surplus(0),t.stake/5n);await(await f.escrow.connect(f.signers[1]).claim(r,sig,{gasLimit:500000})).wait();assert.equal(await f.escrow.surplus(0),t.stake/5n);await(await f.escrow.withdrawPlatform(0,f.wallets[0].address,t.stake/5n)).wait();assert.equal(await f.escrow.surplus(0),0n);}finally{await f.close();}});
test('BEM escrow: exact credit, draw returns both deposits, no duplicate awards',async()=>{const f=await fixture();try{const t=await f.ticket(1);await fund(f,t);const r={id:t.id,winner:2,endedAt:await f.time(),evidence:t.rulesHash},sig=await f.sign('Result',r);await f.advance(61);for(const i of[1,2]){const before=await f.tok.balanceOf(f.wallets[i].address);await(await f.escrow.connect(f.signers[i]).claim(r,sig)).wait();assert.equal(await f.tok.balanceOf(f.wallets[i].address)-before,t.stake);}assert.equal(await f.escrow.liability(1),0n);assert.equal(await f.escrow.surplus(1),0n);}finally{await f.close();}});
test('single deposit timeout and signed cancellation protect original principal; paused exits still work',async()=>{const f=await fixture();try{const t=await f.ticket(),sig=await f.sign('Ticket',t);await(await f.escrow.connect(f.signers[1]).fund(t,sig,{value:t.stake})).wait();await(await f.escrow.setPaused(true)).wait();await assert.rejects(f.escrow.connect(f.signers[1]).refundAndWithdraw.staticCall(t.id,'0x'));await f.advance(181);await(await f.escrow.connect(f.signers[1]).refundAndWithdraw(t.id,'0x',{gasLimit:500000})).wait();assert.equal((await f.escrow.getMatch(t.id)).withdrawn[0],true);assert.equal(await f.escrow.liability(0),0n);const absent=await f.ticket();await(await f.escrow.cancel(absent.id,await f.sign('Cancel',{id:absent.id}))).wait();await(await f.escrow.setPaused(false)).wait();await assert.rejects(f.escrow.connect(f.signers[1]).fund.staticCall(absent,await f.sign('Ticket',absent),{value:absent.stake}));}finally{await f.close();}});
test('strict amount precision and final result cannot be changed on later requests',()=>{assert.equal(amountRaw('0.01',0),'10000000000000000');assert.equal(amountRaw('1',1),'100000000');for(const x of['-1','0','NaN','1e3','0.0001','100001'])assert.throws(()=>amountRaw(x,1));const p={payment:{},s:Array(10).fill(0)};p.s[7]=1;finishPayment(p,'finished',100000);const copy=JSON.stringify(p.payment);finishPayment(p,'cancelled',200000);assert.equal(JSON.stringify(p.payment),copy);assert.equal(normalized(artifact.runtime),normalized(artifact.runtime));});
test('one collect transaction settles mixed wins/refunds and ignores already withdrawn matches',async()=>{const f=await fixture();try{const a=await f.ticket(),b=await f.ticket();await fund(f,a);await(await f.escrow.connect(f.signers[1]).fund(b,await f.sign('Ticket',b),{value:b.stake})).wait();const result={id:a.id,winner:0,endedAt:await f.time(),evidence:a.rulesHash},cancel={id:b.id,winner:2,endedAt:0,evidence:'0x'+'0'.repeat(64)},sigs=[await f.sign('Result',result),await f.sign('Cancel',{id:b.id})];await f.advance(61);await(await f.escrow.connect(f.signers[1]).collect([result,cancel],[false,true],sigs)).wait();const ms=await f.escrow.getMatches([a.id,b.id]);assert.deepEqual(ms.map(m=>m.withdrawn[0]),[true,true]);assert.equal(await f.escrow.liability(0),0n);assert.equal(await f.escrow.surplus(0),a.stake/5n);await(await f.escrow.connect(f.signers[1]).collect([result,cancel],[false,true],sigs)).wait();assert.equal(await f.escrow.surplus(0),a.stake/5n);}finally{await f.close();}});
test('forged, cross-chain and non-participant requests cannot move deposits',async()=>{const f=await fixture();try{const t=await f.ticket();const forged=await f.wallets[4].signTypedData({name:'TapeOutEmber',version:'1',chainId:31337,verifyingContract:await f.escrow.getAddress()},{Ticket:types.Ticket},t);await assert.rejects(f.escrow.connect(f.signers[1]).fund.staticCall(t,forged,{value:t.stake}));const wrongChain=await f.wallets[3].signTypedData({name:'TapeOutEmber',version:'1',chainId:196,verifyingContract:await f.escrow.getAddress()},{Ticket:types.Ticket},t);await assert.rejects(f.escrow.connect(f.signers[1]).fund.staticCall(t,wrongChain,{value:t.stake}));await fund(f,t);await assert.rejects(f.escrow.connect(f.signers[4]).refundAndWithdraw.staticCall(t.id,await f.sign('Cancel',{id:t.id})));await assert.rejects(f.escrow.connect(f.signers[4]).withdrawPlatform.staticCall(0,f.wallets[4].address,1));assert.equal(await f.escrow.liability(0),t.stake*2n);}finally{await f.close();}});

import {openArenaDatabase} from '../server/sqlite-db.mjs';
test('server plans -> real EVM funding -> durable outcome -> one payout and history recovery',async()=>{
 const f=await fixture(196),db=openArenaDatabase(':memory:',new URL('../server/schema.sql',import.meta.url)),finance=new EmberFinance(db,null,{depositRoomsEnabled:true});const now=Date.now;
 try{
  finance.config={escrow:await f.escrow.getAddress()};finance.signer=f.wallets[3];finance.rpc=async(_i,method,params)=>f.raw.request({method,params:params.map(v=>v==='safe'?'latest':v)});
  await finance.verify();assert.equal(finance.public().enabled,true);
  const users=[f.wallets[1].address.toLowerCase(),f.wallets[2].address.toLowerCase()],q=await finance.terms(users[0],{asset:0,amount:'0.01'}),p={wallets:users,payment:{...q,fundUntil:await f.time()+180},s:Array(80).fill(0)};
  await db.prepare("INSERT INTO arena_rooms VALUES(?,'funding',0,?,?,0,?)").bind('ABCDEF',now(),now()+600000,JSON.stringify(p)).run();
  for(let i=0;i<2;i++){const plan=await finance.handle(users[i],{action:'fund',key:q.key});await(await f.signers[i+1].sendTransaction(plan)).wait();const row=await db.prepare('SELECT payload FROM arena_rooms WHERE code=?').bind('ABCDEF').first(),payload=JSON.parse(row.payload);payload.payment.checkedAt=0;await db.prepare('UPDATE arena_rooms SET payload=? WHERE code=?').bind(JSON.stringify(payload),'ABCDEF').run();}
  finance.safeBlock=null;const v=await finance.sync(users[0],q.key);assert.deepEqual(v.chainPaid,[true,true]);
  const row=await db.prepare('SELECT payload FROM arena_rooms WHERE code=?').bind('ABCDEF').first(),payload=JSON.parse(row.payload);payload.s[7]=0;payload.s[4]=2;finishPayment(payload,'finished',(await f.time())*1000);await db.prepare("UPDATE arena_rooms SET payload=?,status='finished' WHERE code=?").bind(JSON.stringify(payload),'ABCDEF').run();
  await f.advance(61);Date.now=()=>now()+62000;finance.safeBlock=null;
  const h=await finance.handle(users[0],{action:'claimable'});assert.equal(h.matches[0].payout,'18000000000000000');
  const plan=await finance.handle(users[0],{action:'collect',keys:[q.key]});await(await f.signers[1].sendTransaction(plan)).wait();Date.now=()=>now()+68000;finance.safeBlock=null;
  const result=await finance.handle(users[0],{action:'status-keys',keys:[q.key]});assert.equal(result.matches[0].withdrawn,true);const current=await f.escrow.getMatch(q.key);const stale={...current,state:0,paid:[false,false],withdrawn:[false,false],payout:[0n,0n]};assert.equal((await finance.storeSnapshot(users[0],q.key,stale,'0x0')).withdrawn,true,'late reads cannot regress confirmed withdrawal');assert.equal((await finance.handle(users[0],{action:'claimable'})).matches.length,0);
  assert.equal((await finance.handle(users[0],{action:'claim',key:q.key})).complete,true);
  await assert.rejects(finance.handle(f.wallets[4].address.toLowerCase(),{action:'claim',key:q.key}),/PARTICIPANT/);
 }finally{Date.now=now;finance.close();db.close();await f.close();}
});

test('unclaimed winner cannot be erased by a 24-hour refund; signed abandoned-room refund remains available',async()=>{const f=await fixture();try{const t=await f.ticket();await fund(f,t);const r={id:t.id,winner:0,endedAt:await f.time(),evidence:t.rulesHash},sig=await f.sign('Result',r);await f.advance(86401);await assert.rejects(f.escrow.connect(f.signers[2]).refundExpired.staticCall(t.id));await assert.rejects(f.escrow.connect(f.signers[2]).refundAndWithdraw.staticCall(t.id,'0x'));await(await f.escrow.connect(f.signers[1]).claim(r,sig)).wait();assert.equal((await f.escrow.getMatch(t.id)).payout[0],t.stake*18n/10n);const cancelled=await f.ticket();await fund(f,cancelled);const cs=await f.sign('Cancel',{id:cancelled.id});await(await f.escrow.connect(f.signers[1]).refundAndWithdraw(cancelled.id,cs)).wait();assert.equal((await f.escrow.getMatch(cancelled.id)).payout[0],cancelled.stake);}finally{await f.close();}});

test('treasury allows exact BEM dust and pause; protected liability and wallet nonce recovery remain intact',async()=>{const f=await fixture(196),db=openArenaDatabase(':memory:',new URL('../server/schema.sql',import.meta.url)),finance=new EmberFinance(db,null,{depositRoomsEnabled:true});try{finance.config={escrow:await f.escrow.getAddress()};finance.signer=f.wallets[3];finance.rpc=async(_i,method,params)=>f.raw.request({method,params:params.map(v=>v==='safe'?'latest':v)});await finance.verify();await(await f.tok.claim()).wait();await(await f.tok.transfer(finance.config.escrow,123n)).wait();finance.safeBlock=null;const treasury=await finance.admin({action:'ember-treasury'});assert.equal(treasury.assets[1].withdrawable,'123');const r={kind:'withdraw',asset:1,amount:'123',to:f.wallets[0].address,escrow:finance.config.escrow};const plan=await finance.adminPlan(r);assert.equal(plan.chainId,196);const nonce=await f.raw.request({method:'eth_getTransactionCount',params:[f.wallets[0].address,'pending']});const recovery=await finance.transactionStatus({...r,from:f.wallets[0].address,nonce});assert.equal(recovery.status,'resumable');assert.equal(recovery.plan.data,plan.data);await(await f.signers[0].sendTransaction(plan)).wait();finance.safeBlock=null;assert.equal((await finance.transactionStatus({...r,from:f.wallets[0].address,nonce})).status,'consumed');await assert.rejects(finance.adminPlan(r),/SURPLUS_ONLY/);await assert.rejects(finance.adminPlan({...r,to:finance.config.escrow}),/BAD_TRANSACTION/);const pause=await finance.adminPlan({kind:'pause',paused:true,escrow:finance.config.escrow});await(await f.signers[0].sendTransaction(pause)).wait();finance.safeBlock=null;assert.equal((await finance.admin({action:'ember-treasury'})).paused,true);await assert.rejects(f.escrow.renounceOwnership.staticCall());}finally{finance.close();db.close();await f.close();}});

test('missing-hash player payment recovery checks original nonce and calldata commitment',async()=>{const f=await fixture(196),db=openArenaDatabase(':memory:',new URL('../server/schema.sql',import.meta.url)),finance=new EmberFinance(db,null,{depositRoomsEnabled:true});try{finance.config={escrow:await f.escrow.getAddress()};finance.signer=f.wallets[3];finance.rpc=async(_i,method,params)=>f.raw.request({method,params:params.map(v=>v==='safe'?'latest':v)});await finance.verify();const users=f.wallets.slice(1,3).map(w=>w.address.toLowerCase()),q=await finance.terms(users[0],{asset:0,amount:'0.01'}),p={wallets:users,payment:{...q,fundUntil:await f.time()+180},s:Array(80).fill(0)};await db.prepare("INSERT INTO arena_rooms VALUES(?,'funding',0,?,?,0,?)").bind('ABCDEF',Date.now(),Date.now()+600000,JSON.stringify(p)).run();const plan=await finance.handle(users[0],{action:'fund',key:q.key}),nonce=await f.raw.request({method:'eth_getTransactionCount',params:[users[0],'pending']}),{createHash}=await import('node:crypto');const r={from:users[0],kind:'fund',key:q.key,nonce,commitment:'0x'+createHash('sha256').update(JSON.stringify([plan.to.toLowerCase(),plan.data,BigInt(plan.value).toString()])).digest('hex')};const recovered=await finance.paymentStatus(users[0],r);assert.equal(recovered.status,'resumable');assert.equal(recovered.plan.nonce,nonce);await assert.rejects(finance.paymentStatus(users[0],{...r,commitment:'0x'+'0'.repeat(64)}),/PAYMENT_MISMATCH/);await assert.rejects(finance.paymentStatus(users[1],r),/BAD_TRANSACTION/);await(await f.signers[1].sendTransaction(recovered.plan)).wait();finance.safeBlock=null;assert.equal((await finance.paymentStatus(users[0],r)).status,'consumed');}finally{finance.close();db.close();await f.close();}});


test('upgrade retains old escrow, refuses active paid rooms and respects the new contract pause',async()=>{
 const f=await fixture(196),db=openArenaDatabase(':memory:',new URL('../server/schema.sql',import.meta.url));const {mkdtempSync,rmSync}=await import('node:fs'),{tmpdir}=await import('node:os'),folder=mkdtempSync(tmpdir()+'/ember-upgrade-'),finance=new EmberFinance(db,folder+'/finance.json');
 try{finance.config={escrow:await f.escrow.getAddress(),refereeKey:f.wallets[3].privateKey};finance.signer=f.wallets[3];finance.rpc=async(_i,method,params)=>f.raw.request({method,params:params.map(v=>v==='safe'?'latest':v)});await finance.verify();const next=await new ContractFactory(artifact.abi,artifact.bytecode,f.signers[0]).deploy(f.wallets[3].address,f.wallets[0].address,BEM);await next.waitForDeployment();await(await next.setPaused(true)).wait();finance.safeBlock=null;
 await db.prepare("INSERT INTO arena_rooms VALUES(?,'funding',0,?,?,0,?)").bind('ABCDEF',Date.now(),Date.now()+600000,JSON.stringify({payment:{key:'test'}})).run();await assert.rejects(finance.activate(await next.getAddress()),/UPGRADE_ACTIVE/);await db.prepare("DELETE FROM arena_rooms WHERE code=?").bind('ABCDEF').run();const v=await finance.activate(await next.getAddress());assert.equal(v.paused,true);assert.equal(v.enabled,false);assert.equal(v.configured,true);assert.deepEqual(v.legacy,[{escrow:await f.escrow.getAddress()}]);const old=await finance.admin({action:'ember-treasury',address:await f.escrow.getAddress()});assert.equal(old.escrow,await f.escrow.getAddress());assert.equal(old.paused,false);assert.equal(finance.public().enabled,false);assert.equal(JSON.parse(readFileSync(folder+'/finance.json')).refereeKey,f.wallets[3].privateKey);
 }finally{finance.close();db.close();await f.close();rmSync(folder,{recursive:true,force:true});}
});
