import test from 'node:test';import assert from 'node:assert/strict';
import {makePayments,payText} from '../public/payments.mjs';
const address='0x'+'1'.repeat(40),key='0x'+'a'.repeat(64);
const tick=()=>new Promise(r=>setTimeout(r,2));
function fixture(options={}){
 const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{id,hidden:false,disabled:false,open:false,value:'0.01',textContent:'',dataset:{},setAttribute(){},blur(){},replaceChildren(){},append(){}});return elements.get(id);};
 const modes=['free','deposit'].map(stakeMode=>({...el(stakeMode),dataset:{stakeMode}}));const doc={hidden:false,getElementById:el,querySelectorAll:q=>q==='[data-stake-mode]'?modes:[],createElement:()=>({append(){}})};
 const memory=options.memory||new Map(),intervals=new Map(),requests=[],sends=[];let serial=0,approved=options.approved||false,paid=false;
 const win={localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},setInterval(fn){intervals.set(++serial,fn);return serial;},clearInterval(id){intervals.delete(id);},setTimeout(fn){queueMicrotask(fn);return 1;}};
 let current={slot:0},view={key,asset:options.asset??0,stake:options.asset===1?'100000000':'10000000000000000',seat:0,chainPaid:[false,false],fundUntil:Math.floor(Date.now()/1000)+180,serverTime:Date.now()};
 const plan={chainId:196,from:address,to:'0x'+'2'.repeat(40),value:'0x0',data:'0x1234'};
 const fetchBefore=globalThis.fetch;globalThis.fetch=async(_,r)=>{const b=JSON.parse(r.body);requests.push(b);let data;
  if(options.gate&&b.action==='fund')await options.gate;
  if(b.action==='config')data={enabled:true};else if(b.action==='sync')data={...view,chainPaid:[paid,false],serverTime:Date.now()};else if(b.action==='approve')data=approved?{complete:true}:plan;else if(b.action==='fund')data=plan;else if(b.action==='payment-status')data={status:options.recovery||'pending'};else data={matches:[]};return{ok:true,json:async()=>data};};
 const wallet={state:{phase:'connected',address,session:'mock',mobile:false},prepareTransaction:async p=>({...p,nonce:'0x4'}),send:async p=>{sends.push(p);if(options.unknown)return undefined;if(view.asset===1&&!approved)approved=true;else if(!options.delayed)paid=true;return'0x'+'b'.repeat(64);},failedReceipt:async()=>false,reopen(){}};
 const panels={get open(){return [...elements.values()].some(x=>x.open);},show(d){for(const x of elements.values())x.open=false;d.open=true;},close(d){d.open=false;}};
 const ui=makePayments({wallet,panels,currentRoom:()=>current,leave:async()=>ui.closed(),window:win,document:doc,depositRoomsEnabled:options.enabled??true});
 return{ui,el,wallet,requests,sends,memory,view,modes,paid(v){paid=v;},approved(v){approved=v;},async click(id){el(id).onclick?.();for(let i=0;i<12;i++)await tick();},async room(p={}){Object.assign(view,p);ui.room({...view,paid:[paid,false],...p});for(let i=0;i<12;i++)await tick();},close(){ui.closed();globalThis.fetch=fetchBefore;}};
}
test('waiting host sees no payment modal or chain sync; first funding opens once and manual reopening remains available',async()=>{const f=fixture();try{await f.room({fundUntil:null});assert.equal(f.el('paymentDialog').open,false);assert.equal(f.requests.filter(x=>x.action==='sync').length,0);await f.room({fundUntil:Math.floor(Date.now()/1000)+180});assert.equal(f.el('paymentDialog').open,true);await f.click('paymentClose');await f.room();assert.equal(f.el('paymentDialog').open,false);await f.click('fundingOpen');assert.equal(f.el('paymentDialog').open,true);}finally{f.close();}});
test('OKB exposes a single payment and becomes ready only from chain evidence',async()=>{const f=fixture();try{await f.room();assert.equal(f.el('paymentApprove').hidden,true);assert.equal(f.el('paymentPay').disabled,false);assert.equal(f.el('paymentPay').textContent,'支付押金');await f.click('paymentPay');assert.equal(f.sends.length,1);assert.equal(f.el('paymentPay').disabled,true);assert.match(f.el('paymentStatus').textContent,/已付款/);}finally{f.close();}});
test('BEM payment is disabled until allowance is verified; allowance already granted skips another approval',async()=>{for(const existing of [false,true]){const f=fixture({asset:1,approved:existing});try{await f.room();assert.equal(f.el('paymentPay').disabled,!existing);if(!existing){await f.click('paymentPay');assert.equal(f.sends.length,0);await f.click('paymentApprove');}assert.equal(f.el('paymentPay').disabled,false);await f.click('paymentPay');assert.equal(f.sends.length,existing?1:2);assert.equal(f.el('paymentPay').disabled,true);}finally{f.close();}}});
test('closing a room while checking payment prevents a late wallet send',async()=>{let release;const gate=new Promise(r=>release=r),f=fixture({gate});try{await f.room();await f.click('paymentPay');f.ui.closed();release();for(let i=0;i<15;i++)await tick();assert.equal(f.sends.length,0);assert.equal(f.memory.size,0);}finally{f.close();}});
test('unknown payment keeps original journal and does not resend on refresh or another click',async()=>{const f=fixture({unknown:true});try{await f.room();await f.click('paymentPay');assert.equal(f.sends.length,1);assert.equal(f.memory.size,1);await f.click('paymentRefresh');await f.click('paymentPay');assert.equal(f.sends.length,1);assert.match(f.el('paymentStatus').textContent,/未返回/);f.paid(true);await f.click('paymentRefresh');assert.equal(f.el('paymentPay').disabled,true);}finally{f.close();}});
test('cancelled and expired rooms never enable payment; amount editor retains prior value on invalid input',async()=>{const f=fixture();try{await f.room({fundUntil:Math.floor(Date.now()/1000)-1});assert.equal(f.el('paymentPay').disabled,true);assert.match(f.el('paymentStatus').textContent,/核验/);f.modes[1].onclick();await f.click('stakeEdit');f.el('amountInput').value='0.0001';f.el('amountForm').onsubmit({preventDefault(){}});assert.match(f.el('amountError').textContent,/有效金额/);assert.equal(f.ui.choice().amount,'0.01');f.el('amountInput').value='0.025';f.el('amountForm').onsubmit({preventDefault(){}});assert.equal(f.ui.choice().amount,'0.025');assert.equal(f.el('stakeEdit').textContent,'0.025');assert.equal(f.el('amountDialog').open,false);}finally{f.close();}});

test('closed deposits cannot be selected or paid while history remains available',async()=>{const f=fixture({enabled:false});try{await tick();assert.equal(f.modes[1].disabled,true);f.modes[1].onclick();assert.equal(f.ui.choice(),null);await f.room();await f.click('paymentPay');assert.equal(f.sends.length,0);assert.equal(f.requests.some(x=>x.action==='fund'),false);await f.ui.history();assert.ok(f.requests.some(x=>x.action==='history'));}finally{f.close();}});

test('expired countdown never conceals safe-confirmed own payment',async()=>{const f=fixture();try{await f.room({fundUntil:Math.floor(Date.now()/1000)-1});assert.match(f.el('paymentStatus').textContent,/核验/);f.paid(true);await f.room();assert.match(f.el('paymentStatus').textContent,/已付款/);assert.equal(f.el('paymentPay').disabled,true);}finally{f.close();}});

// A submitted transaction can outlive all five foreground checks and an app restart.
test('slow safe head never re-enables payment, including refresh, reopen, app restart and consumed nonce',async()=>{
 const memory=new Map();for(let restart=0;restart<2;restart++){const f=fixture({delayed:true,memory,recovery:'consumed'});try{
 await f.room();if(!restart)await f.click('paymentPay');assert.equal(f.el('paymentPay').disabled,true);assert.equal(f.el('paymentPay').textContent,'等待确认');assert.equal(memory.size,1);
 await f.click('paymentClose');await f.click('fundingOpen');await f.click('paymentRefresh');await f.click('paymentPay');assert.equal(f.sends.length,restart?0:1);assert.equal(memory.size,1);assert.equal(f.el('paymentPay').disabled,true);
 if(restart){f.paid(true);await f.click('paymentRefresh');assert.equal(memory.size,0);assert.equal(f.el('paymentPay').disabled,true);assert.match(f.el('paymentStatus').textContent,/已付款/);}
 }finally{f.close();}}
});
test('latest-chain payment prevents payment from another device without pretending it is safe',async()=>{const f=fixture();try{await f.room({observedPaid:[true,false]});assert.equal(f.el('paymentPay').disabled,true);assert.match(f.el('paymentStatus').textContent,/已到账.*等待对方/);await f.click('paymentPay');assert.equal(f.sends.length,0);}finally{f.close();}});
test('known hash is never resent even if recovery reports resumable; safe-verified failure permits retry',async()=>{
 for(const recovery of ['resumable','failed']){const f=fixture({delayed:true,recovery});try{await f.room();await f.click('paymentPay');await f.click('paymentRefresh');assert.equal(f.sends.length,1);assert.equal(f.el('paymentPay').disabled,recovery!=='failed');assert.equal(f.memory.size,recovery==='failed'?0:1);}finally{f.close();}}
});

test('pending-payment feedback is translated in both language modes',()=>{const before=globalThis.window;try{for(const lang of ['zh','en']){globalThis.window={location:{href:'https://game.example/?lang='+lang}};assert.equal(payText('awaiting'),lang==='en'?'Awaiting confirmation':'等待确认');assert.match(payText('PAYMENT_PENDING'),lang==='en'?/waiting for the opponent/:/等待对方/);}}finally{globalThis.window=before;}});
