import test from 'node:test';import assert from 'node:assert/strict';import {makePayments,payText} from '../public/payments.mjs';
const owner='0x'+'1'.repeat(40),escrow='0x'+'2'.repeat(40),key=n=>'0x'+n.toString(16).padStart(64,'0');
const match=(n,extra={})=>({key:key(n),escrow,asset:0,stake:'10000000000000000',payout:'18000000000000000',endedAt:1,createdAt:1000,claimAt:10,serverTime:10000,seat:0,winner:0,settlementReady:true,withdrawn:false,...extra});
function fixture(rows,options={}){
 const elements=new Map();function element(){return{children:[],dataset:{},textContent:'',hidden:false,disabled:false,value:'0.01',setAttribute(){},replaceChildren(){this.children=[]},append(...nodes){this.children.push(...nodes)},blur(){}}}const el=id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id)};
 const doc={hidden:false,getElementById:el,querySelectorAll:()=>[],createElement:element},memory=new Map(),requests=[],sends=[],claimed=new Set();let planKeys=[];
 const win={localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},setTimeout:fn=>{queueMicrotask(fn);return 1},clearInterval(){},setInterval(){return 1}};
 const before=globalThis.fetch;globalThis.fetch=async(_,r)=>{const b=JSON.parse(r.body);requests.push(b);if(options.gate&&b.action==='claimable')await options.gate;let data;
 const project=m=>({...m,withdrawn:m.withdrawn||claimed.has(m.key)});
 if(b.action==='config')data={enabled:true};else if(b.action==='history')data={matches:rows.slice(b.offset||0,(b.offset||0)+20).map(project)};
 else if(b.action==='claimable'){const index=b.cursor?.createdAt||0;data={matches:rows.slice(index,index+20).map(project),nextCursor:index+20<rows.length?{createdAt:index+20,code:'CURSOR'}:null};}
 else if(b.action==='status-keys')data={matches:rows.filter(m=>b.keys.includes(m.key)).map(project)};
 else if(b.action==='sync')data=project(rows.find(m=>m.key===b.key));
 else if(b.action==='collect'||b.action==='claim'){planKeys=b.keys||[b.key];data={chainId:196,from:owner,to:escrow,value:'0x0',data:'0x1234'};}
 else if(b.action==='payment-status')data={status:'pending'};else throw Error(b.action);
 return{ok:true,json:async()=>data};};
 const wallet={state:{address:owner,session:'session',phase:'connected',mobile:false},prepareTransaction:async p=>({...p,nonce:'0x1'}),send:async p=>{sends.push({p,keys:[...planKeys]});if(options.cancel)throw Object.assign(Error('cancel'),{code:4001});if(!options.pending)planKeys.forEach(k=>claimed.add(k));return'0x'+'a'.repeat(64)},reopen(){}};
 const panels={show(d){for(const e of elements.values())e.open=false;d.open=true},close(d){d.open=false},get open(){return false}};const ui=makePayments({wallet,panels,currentRoom:()=>null,leave:async()=>{},window:win,document:doc});
 return{ui,el,wallet,requests,sends,memory,claimed,async all(){await el('rewardsAll').onclick()},close(){ui.closed();globalThis.fetch=before}};
}
test('empty and all-withdrawn histories disable claim-all and explicitly include deposits in the empty message',async()=>{for(const rows of [[],[match(1,{withdrawn:true})]]){const f=fixture(rows);try{await f.ui.history();assert.equal(f.el('rewardsSummary').textContent,'没有可领取的奖励或押金');assert.equal(f.el('rewardsAll').disabled,true);await f.all();assert.equal(f.sends.length,0);}finally{f.close()}}});
test('count includes only claimable wins/refunds, not losses, unconfirmed, wait periods or withdrawn entries',async()=>{const f=fixture([match(1),match(2,{cancelled:true,payout:'10000000000000000'}),match(3,{withdrawn:true}),match(4,{payout:'0',winner:1}),match(5,{settlementReady:false}),match(6,{claimAt:11000})]);try{await f.ui.history();assert.equal(f.el('rewardsSummary').textContent,'可领取 2 笔');await f.all();assert.equal(f.sends.length,1);assert.deepEqual(f.sends[0].keys,[key(1),key(2)]);assert.equal(f.el('rewardsSummary').textContent,'没有可领取的奖励或押金');assert.equal(f.el('paymentDone').hidden,false);await f.ui.history();assert.equal(f.el('rewardsAll').disabled,true);}finally{f.close()}});
test('claim-all covers older pages and batches at most 20, with one wallet confirmation per batch',async()=>{const f=fixture(Array.from({length:45},(_,i)=>match(i+1)));try{await f.ui.history();assert.equal(f.el('rewardsSummary').textContent,'可领取 45 笔');await f.all();assert.deepEqual(f.sends.map(x=>x.keys.length),[20,20,5]);assert.equal(new Set(f.sends.flatMap(x=>x.keys)).size,45);assert.equal(f.memory.size,0);assert.equal(f.el('rewardsAll').disabled,true);}finally{f.close()}});
test('double clicks cannot start two batches while loading candidates',async()=>{let release;const f=fixture([match(1)],{gate:new Promise(r=>release=r)});try{const h=f.ui.history();release();await h;await Promise.all([f.all(),f.all()]);assert.equal(f.sends.length,1);}finally{f.close()}});
test('cancelled claims stay claimable; pending transactions retain their original journal and are never resent',async()=>{for(const options of [{cancel:true},{pending:true}]){const f=fixture([match(1)],options);try{await f.ui.history();await f.all();assert.equal(f.el('rewardsSummary').textContent,'可领取 1 笔');assert.equal(f.sends.length,1);if(options.pending){await f.all();assert.equal(f.sends.length,1);assert.equal(f.memory.size,1);f.claimed.add(key(1));await f.all();assert.equal(f.memory.size,0);assert.equal(f.el('rewardsAll').disabled,true);}else assert.equal(f.memory.size,0);}finally{f.close()}}});
test('wallet change during candidate loading cannot submit a transaction for the previous account',async()=>{let release;const f=fixture([match(1)],{gate:new Promise(r=>release=r)});try{const h=f.ui.history();release();await h;let go;globalThis.fetch=((base)=>async(...args)=>{if(JSON.parse(args[1].body).action==='claimable')await new Promise(r=>go=r);return base(...args)})(globalThis.fetch);const claim=f.all();await new Promise(r=>setImmediate(r));f.wallet.state.address='0x'+'9'.repeat(40);go();await claim;assert.equal(f.sends.length,0);}finally{f.close()}});
test('individual claim updates the shared summary immediately after verified receipt',async()=>{const f=fixture([match(1)]);try{await f.ui.history();await f.el('rewardList').children[0].children[2].onclick();assert.equal(f.sends.length,1);assert.equal(f.el('rewardsAll').disabled,true);assert.equal(f.el('rewardsSummary').textContent,'没有可领取的奖励或押金');}finally{f.close()}});
test('reward count and empty states have Chinese and English translations',()=>{const old=globalThis.window;try{globalThis.window={location:{href:'https://game.example/?lang=en'}};assert.equal(payText('claimCount'),' {n} claims available'.trim());assert.equal(payText('none'),'No rewards or deposits available to claim');}finally{globalThis.window=old}});
