import test from 'node:test';import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {openArenaDatabase} from '../server/sqlite-db.mjs';import {handleArena} from '../server/arena-server.mjs';import {EmberFinance} from '../server/finance.mjs';
const schema=new URL('../server/schema.sql',import.meta.url),origin='https://ember.example';
const hash=s=>createHash('sha256').update(s).digest('hex');
async function fixture(){const db=openArenaDatabase(':memory:',schema);const wallets=['0x'+'1'.repeat(40),'0x'+'2'.repeat(40)],sessions=[randomBytes(24).toString('hex'),randomBytes(24).toString('hex')];for(let i=0;i<2;i++){await db.prepare('INSERT INTO ember_profiles VALUES(?,?,?)').bind(wallets[i],'Player '+i,Date.now()).run();await db.prepare('INSERT INTO ember_sessions VALUES(?,?,?,?)').bind(hash(sessions[i]),wallets[i],origin,Date.now()+3600000).run();}const finance={public:()=>({enabled:true}),balances:async()=>({}),terms:async()=>({key:'0x'+randomBytes(32).toString('hex'),asset:0,stake:'10000000000000000',escrow:'0x'+'3'.repeat(40),paid:[false,false],createdAt:Date.now()})};return{db,wallets,sessions,finance,async call(body){const res=await handleArena(new Request(origin+'/api/arena',{method:'POST',headers:{'content-type':'application/json',origin},body:JSON.stringify(body)}),db,[],finance);return{status:res.status,...await res.json()};}};}
test('created room remains in public list; payment terms cannot leak credentials; funding does not start fight',async()=>{const f=await fixture();try{const a=await f.call({action:'create',character:0,walletSession:f.sessions[0],deposit:{asset:0,amount:'0.01'}});assert.equal(a.status,'waiting');const list=await f.call({action:'list'});assert.equal(list.rooms[0].code,a.code);assert.equal(list.rooms[0].stake,'10000000000000000');assert.equal(JSON.stringify(list).includes(a.token),false);const b=await f.call({action:'join',code:a.code,character:1,walletSession:f.sessions[1]});assert.equal(b.status,'funding');assert.equal(b.state[1],0);let s=await f.call({action:'input',code:a.code,token:a.token,seq:1,mask:16,edges:16});assert.equal(s.status,'funding');let row=await f.db.prepare('SELECT * FROM arena_rooms WHERE code=?').bind(a.code).first(),p=JSON.parse(row.payload);p.payment.paid=[true,false];await f.db.prepare('UPDATE arena_rooms SET payload=? WHERE code=?').bind(JSON.stringify(p),a.code).run();s=await f.call({action:'input',code:a.code,token:a.token,seq:2,mask:0,edges:0});assert.equal(s.status,'funding');row=await f.db.prepare('SELECT * FROM arena_rooms WHERE code=?').bind(a.code).first();p=JSON.parse(row.payload);p.payment.paid=[true,true];await f.db.prepare('UPDATE arena_rooms SET payload=? WHERE code=?').bind(JSON.stringify(p),a.code).run();s=await f.call({action:'input',code:a.code,token:a.token,seq:3,mask:0,edges:0});assert.equal(s.status,'playing');assert.equal(s.state[1],1);await f.call({action:'leave',code:b.code,token:b.token});row=await f.db.prepare('SELECT * FROM arena_rooms WHERE code=?').bind(a.code).first();p=JSON.parse(row.payload);assert.equal(p.payment.winner,0);assert.ok(p.payment.endedAt);assert.ok(p.payment.evidence);}finally{f.db.close();}});
test('funding departure cancels instead of awarding a win; deposit room cannot be reused by same wallet',async()=>{const f=await fixture();try{const a=await f.call({action:'create',character:0,walletSession:f.sessions[0],deposit:{asset:0,amount:'0.01'}});assert.equal((await f.call({action:'join',code:a.code,character:1,walletSession:f.sessions[0]})).error,'SAME_WALLET');const b=await f.call({action:'join',code:a.code,character:1,walletSession:f.sessions[1]});await f.call({action:'leave',code:b.code,token:b.token});const row=await f.db.prepare('SELECT * FROM arena_rooms WHERE code=?').bind(a.code).first(),p=JSON.parse(row.payload);assert.equal(row.status,'cancelled');assert.equal(p.payment.cancelled,true);assert.equal(p.payment.winner,undefined);}finally{f.db.close();}});
test('unconfigured escrow rejects paid creation; free room still works',async()=>{const f=await fixture();try{f.finance.public=()=>({enabled:false});f.finance.terms=async()=>{throw Object.assign(Error('ESCROW_UNAVAILABLE'),{status:409})};assert.equal((await f.call({action:'create',character:0,walletSession:f.sessions[0],deposit:{asset:0,amount:'1'}})).error,'ESCROW_UNAVAILABLE');const a=await f.call({action:'create',character:0,walletSession:f.sessions[0]});assert.equal(a.status,'waiting');const b=await f.call({action:'join',code:a.code,character:1,walletSession:f.sessions[1]});assert.equal(b.status,'playing');}finally{f.db.close();}});

test('legacy quick matching cannot create or bypass a paid room',async()=>{const f=await fixture();try{const r=await f.call({action:'match',character:0,walletSession:f.sessions[0],deposit:{asset:0,amount:'0.01'}});assert.equal(r.error,'PAID_MATCH_REQUIRES_ROOM');assert.equal((await f.call({action:'list'})).rooms.length,0);}finally{f.db.close();}});

test('same-wallet concurrent create is atomic; an offline unpaired room cannot trap a refreshed client',async()=>{const f=await fixture();try{f.finance.terms=async()=>{await new Promise(r=>setTimeout(r,20));return{key:'0x'+randomBytes(32).toString('hex'),asset:0,stake:'10000000000000000',escrow:'0x'+'3'.repeat(40),paid:[false,false],createdAt:Date.now()}};const body={action:'create',character:0,walletSession:f.sessions[0],deposit:{asset:0,amount:'0.01'}};const results=await Promise.all([f.call(body),f.call(body)]);assert.equal(results.filter(r=>r.status==='waiting').length,1);assert.equal(results.filter(r=>r.error==='ACTIVE_ROOM').length,1);await f.db.prepare('UPDATE arena_rooms SET updated=?').bind(Date.now()-16000).run();const fresh=await f.call(body);assert.equal(fresh.status,'waiting');}finally{f.db.close();}});

test('anonymous and stale-session players can create/join free rooms; room secrets still protect controls',async()=>{const f=await fixture();try{
 const a=await f.call({action:'create',character:0}),other=await f.call({action:'create',character:1,walletSession:'expired'});assert.equal(a.status,'waiting');assert.equal(other.status,'waiting');assert.notEqual(a.token,other.token);
 const b=await f.call({action:'join',code:a.code,character:1,walletSession:'expired'});assert.equal(b.status,'playing');assert.equal(b.payment,null);
 assert.equal((await f.call({action:'input',code:a.code,token:other.token,seq:1,mask:2,edges:0})).status,401);
 assert.equal((await f.call({action:'leave',code:a.code,token:other.token})).status,401);
 assert.equal((await f.call({action:'leave',code:a.code,token:b.token})).ok,true);
 const p=JSON.parse((await f.db.prepare('SELECT payload FROM arena_rooms WHERE code=?').bind(a.code).first()).payload);assert.deepEqual(p.wallets,['','']);assert.equal(p.payment,undefined);
 }finally{f.db.close();}});
test('free choice cannot bypass deposit admission or origin-bound wallet auth',async()=>{const f=await fixture();try{
 assert.equal((await f.call({action:'create',character:0,deposit:{asset:0,amount:'0.01'}})).error,'LOGIN_REQUIRED');
 const a=await f.call({action:'create',character:0,walletSession:f.sessions[0],deposit:{asset:0,amount:'0.01'}});
 for(const walletSession of [undefined,'expired',randomBytes(24).toString('hex')])assert.equal((await f.call({action:'join',code:a.code,character:1,deposit:null,walletSession})).error,'LOGIN_REQUIRED');
 const row=await f.db.prepare('SELECT status,payload FROM arena_rooms WHERE code=?').bind(a.code).first();assert.equal(row.status,'waiting');assert.equal(JSON.parse(row.payload).tokens[1],'');
 }finally{f.db.close();}});
test('new passwords are rejected; legacy private rooms are neither exposed nor unlocked',async()=>{const f=await fixture();try{
 assert.equal((await f.call({action:'create',character:0,password:'secret'})).error,'PASSWORD_ROOMS_DISABLED');const a=await f.call({action:'create',character:0});
 const p=JSON.parse((await f.db.prepare('SELECT payload FROM arena_rooms WHERE code=?').bind(a.code).first()).payload);p.lock={salt:'old',hash:'old'};await f.db.prepare('UPDATE arena_rooms SET payload=? WHERE code=?').bind(JSON.stringify(p),a.code).run();
 assert.equal((await f.call({action:'list'})).rooms.length,0);assert.equal((await f.call({action:'join',code:a.code,character:1})).error,'PASSWORD_ROOMS_DISABLED');assert.equal((await f.call({action:'leave',code:a.code,token:a.token})).ok,true);
 }finally{f.db.close();}});
test('anonymous free play retains the existing IP admission throttle',async()=>{const f=await fixture();try{for(let i=0;i<20;i++)assert.equal((await f.call({action:'create',character:0})).status,'waiting');assert.equal((await f.call({action:'create',character:0})).status,429);}finally{f.db.close();}});
